---
- hosts: webserver
  become: true
  tasks:
   - name: install apache
     yum: name=httpd state=present

   - name: Start apache
     service:
       name: httpd
       state: started

   - name: Deploy files
     copy:
        src: index.html
        dest: /var/www/html
